package DayTwo;
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class ProblemTwo {
    public static void main(String[] args){
        int limit = 4_000_000;
        int n1 = 0; //Almacena el penultimo valor de la secuencia
        int n2 = 1; //Almacena el ultimo valor de la secuencia
        int sum = 0; //Key para sumar n1 y n2 para obtener el siguiente valor de la secuencia.

        while (n2 < limit){
            int result = n1 + n2;
            if (result % 2 == 0)
                sum += result;

            n1 = n2;
            n2 = result;
        }
        System.out.println(sum);
    }
}
